### ISSUE TITLE
frontend is not deployed

### ISSUE THREAD

**Issue by theburningmonk** [stackery/wild-rydes-workshop#17]
I'm following the latest instruction, but the frontend is not deployed.

There are couple of things that confuses me too. For example, in this step, we're told to use `src/site` as source directory
![image](https://user-images.githubusercontent.com/546969/87423032-f196fa00-c5d9-11ea-9cce-fea0daf3a86c.png)

but then we only copy the `site` folder to the `src` in the `stackery-wild-rydes` project:
![image](https://user-images.githubusercontent.com/546969/87423188-328f0e80-c5da-11ea-9d33-3992ade04fb9.png)

so the `src/site` folder that's configured as `source directory` doesn't actually exist, right?
![image](https://user-images.githubusercontent.com/546969/87423237-463a7500-c5da-11ea-83ce-f023c0436457.png)

Anyway, at the end of the Frontend module (after running `stackery deploy`), I don't see anything in the S3 bucket and the URL returns 403.

**Comment by txase** [comment]
Hi @theburningmonk!

I forgot to update the stack creation instructions. There are a couple ways to create stacks with Stackery. The current instructions are the simplest because they skip steps that require you to authorize Stackery to access your Git provider (GitHub, GitLab, Bitbucket, etc.). But, the Website builder resource requires us to have Git access so we can fetch sources for the CodeBuild job. If instead you do a "local" deploy, as the instructions end up having you do, then the Website resource is a no-op.

I'll update the stack creation instructions soon, but in the meantime here are the two possible solutions from where you are today:

### Update your existing stack
1. Push your stack to your favorite git provider.
2. Run one of `stackery github setup`, `stackery gitlab setup`, or `stackery bitbucket setup` to authorize Stackery to your Git provider account
2. Run the `stackery repository` command to tell Stackery where your stack's Git repo is located

### Create a new stack stored in a Git provider
1. Login to https://app.stackery.io
2. Click "Create Stack" on the "Stacks" list page
3. Create a new stack backed by your favorite git provider (it will ask you to authorize Stackery if you haven't done so already)
4. Clone the stack down locally to work on it

Both of the above approaches will cause deployments to default to the "codebuild" deployment strategy, which allows the Website builder resource to function correctly. We'll continue working to make the Website resource easier to use in the future :).

Secondly, on the website sources issue, it looks like you're doing everything correctly. We don't currently scaffold the site sources folder as we expect you will bring your own website resources. Here, we instruct you to copy all the files over from this repo.

**Comment by txase** [comment]
I updated the docs to have users create new stacks linked to git repos and do codebuild strategy deployments: 196b750. I'm going to close this issue now, but please reopen if you hit any further issues!

**Comment by theburningmonk** [comment]
thanks @txase it's deployed now, but there was still the issue with the instruction to copy `src/site` from the workshop to the `src` folder, it needs to be copied to the `src/site` in the project folder for it to work, I had to do it manually to get deployment going

**Comment by txase** [comment]
I think I cleared up the instructions for the source site in this commit: 0028ead. 🙏
